import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../data/models/report.dart';
import 'report_provider.dart';

class AddReportPage extends ConsumerStatefulWidget {
  const AddReportPage({super.key});

  @override
  ConsumerState<AddReportPage> createState() => _AddReportPageState();
}

class _AddReportPageState extends ConsumerState<AddReportPage> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _categoryController = TextEditingController();
  final _generatedByController = TextEditingController();
  final _summaryController = TextEditingController();
  bool _saving = false;

  @override
  void dispose() {
    _titleController.dispose();
    _categoryController.dispose();
    _generatedByController.dispose();
    _summaryController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _saving = true);
    final repo = ref.read(reportRepositoryProvider);

    try {
      final report = Report(
        id: '',
        reportCode: 'RPT${DateTime.now().millisecondsSinceEpoch.toString().substring(7)}',
        title: _titleController.text.trim(),
        category: _categoryController.text.trim(),
        generatedBy: _generatedByController.text.trim(),
        summary: _summaryController.text.trim(),
        generatedAt: DateTime.now(),
        status: 'Ready',
      );

      await repo.createReport(report);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Report generated successfully.')),
        );
        ref.invalidate(reportListProvider);
        context.pop();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to generate report: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Generate Report')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              TextFormField(
                controller: _titleController,
                decoration: const InputDecoration(labelText: 'Report Title *'),
                validator: (value) => (value == null || value.trim().isEmpty) ? 'Please enter report title.' : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _categoryController,
                decoration: const InputDecoration(labelText: 'Category *'),
                validator: (value) => (value == null || value.trim().isEmpty) ? 'Please enter category.' : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _generatedByController,
                decoration: const InputDecoration(labelText: 'Generated By *'),
                validator: (value) => (value == null || value.trim().isEmpty) ? 'Please enter author.' : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _summaryController,
                decoration: const InputDecoration(labelText: 'Summary *'),
                minLines: 3,
                maxLines: 6,
                validator: (value) => (value == null || value.trim().isEmpty) ? 'Please enter a summary.' : null,
              ),
              const SizedBox(height: 20),
              FilledButton(
                onPressed: _saving ? null : _submit,
                child: _saving
                    ? const SizedBox(
                        height: 20,
                        width: 20,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Text('Generate Report'),
              )
            ],
          ),
        ),
      ),
    );
  }
}
