// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT6n1JaE91Cfyeb43iloNmfvihvkLY_F0',
    appId: '1:509499765174:ios:a16140e21fd0e3c0a41117',
    messagingSenderId: '509499765174',
    projectId: 'hospital-management-syst-ea0ef',
    storageBucket: 'hospital-management-syst-ea0ef.firebasestorage.app',
    iosBundleId: 'com.example.hospitalManagementSystem',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT6n1JaE91Cfyeb43iloNmfvihvkLY_F0',
    appId: '1:509499765174:ios:a16140e21fd0e3c0a41117',
    messagingSenderId: '509499765174',
    projectId: 'hospital-management-syst-ea0ef',
    storageBucket: 'hospital-management-syst-ea0ef.firebasestorage.app',
    iosBundleId: 'com.example.hospitalManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbFfnBWvaRordGr7daFmcT_bLhNP4Siyc',
    appId: '1:509499765174:web:908ee96587239277a41117',
    messagingSenderId: '509499765174',
    projectId: 'hospital-management-syst-ea0ef',
    authDomain: 'hospital-management-syst-ea0ef.firebaseapp.com',
    storageBucket: 'hospital-management-syst-ea0ef.firebasestorage.app',
    measurementId: 'G-MR6MK2DKMY',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbFfnBWvaRordGr7daFmcT_bLhNP4Siyc',
    appId: '1:509499765174:web:908ee96587239277a41117',
    messagingSenderId: '509499765174',
    projectId: 'hospital-management-syst-ea0ef',
    authDomain: 'hospital-management-syst-ea0ef.firebaseapp.com',
    storageBucket: 'hospital-management-syst-ea0ef.firebasestorage.app',
    measurementId: 'G-MR6MK2DKMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDogbVfh2RPI0vyZ060Op3NwiMaGxAVJjE',
    appId: '1:509499765174:android:70c7537b264d013aa41117',
    messagingSenderId: '509499765174',
    projectId: 'hospital-management-syst-ea0ef',
    storageBucket: 'hospital-management-syst-ea0ef.firebasestorage.app',
  );
}
